export default {
  genin: {
    atributos: [7, 5, 3],
    habilidades: [13, 9, 5],
    elementos: 2,
    vantagens_desvantagens: 7,
    jutsus: 5,
    vontade: 5,
    chakra: 3,
    pontos_bonus: 25,
    vitalidade: 10,
  },
  chunin: {
    atributos: [8, 6, 4],
    habilidades: [14, 14, 14],
    elementos: 3,
    vantagens_desvantagens: 9,
    jutsus: 6,
    vontade: 5,
    chakra: 5,
    pontos_bonus: 25,
    vitalidade: 20,
  },
  jonin: {
    atributos: [10, 8, 6],
    habilidades: [18, 18, 18],
    elementos: 5,
    vantagens_desvantagens: 14,
    jutsus: 10,
    vontade: 5,
    chakra: 10,
    pontos_bonus: 25,
    vitalidade: 30,
  },
  anbu: {
    atributos: [10, 8, 6],
    habilidades: [24, 24, 24],
    elementos: 4,
    vantagens_desvantagens: 10,
    jutsus: 10,
    vontade: 5,
    chakra: 10,
    pontos_bonus: 25,
    vitalidade: 30,
  },
  sanin: {
    atributos: [12, 12, 12],
    habilidades: [30, 30, 30],
    elementos: 10,
    vantagens_desvantagens: 20,
    jutsus: 20,
    vontade: 5,
    chakra: 20,
    pontos_bonus: 25,
    vitalidade: 50,
  },
  hokage: {
    atributos: [17, 17, 17],
    habilidades: [40, 40, 40],
    elementos: 15,
    vantagens_desvantagens: 30,
    jutsus: 30,
    vontade: 10,
    chakra: 30,
    pontos_bonus: 25,
    vitalidade: 100,
  },
};
